CREATE TABLE [dbo].[Proxy]
(
[Id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[JSON] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Proxy] ADD CONSTRAINT [PK_Proxy_Id] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Proxy] ADD CONSTRAINT [UQ_ProxyNameUnique] UNIQUE NONCLUSTERED  ([Name]) ON [PRIMARY]
GO
